def getMaxRepetitions(s1, n1, s2, n2):
    pass
print(getMaxRepetitions("acb", 4, "ab", 2))
print(getMaxRepetitions("acb", 1, "acb", 1))
print(getMaxRepetitions("aaa", 3, "aa", 1))
print(getMaxRepetitions("aaa", 3, "aa", 2))
print(getMaxRepetitions("aaa", 3, "aaa", 2))
print(getMaxRepetitions("aaa", 3, "aaa", 3))
print(getMaxRepetitions("aaa", 3, "aaa", 4))
print(getMaxRepetitions("aaa", 3, "aaa", 5))
print(getMaxRepetitions("aaa", 3, "aaa", 6))
print(getMaxRepetitions("aaa", 3, "aaa", 7))
print(getMaxRepetitions("aaa", 3, "aaa", 8))
print(getMaxRepetitions("aaa", 3, "aaa", 9))
print(getMaxRepetitions("aaa", 3, "aaa", 10))
print(getMaxRepetitions("aaa", 3, "aaa", 11))
print(getMaxRepetitions("aaa", 3, "aaa", 12))
print(getMaxRepetitions("aaa", 3, "aaa", 13))
print(getMaxRepetitions("aaa", 3, "aaa", 14))
print(getMaxRepetitions("aaa", 3, "aaa", 15))
print(getMaxRepetitions("aaa", 3, "aaa", 16))
print(getMaxRepetitions("aaa", 3, "aaa", 17))
print(getMaxRepetitions("aaa", 3, "aaa", 18))
print(getMaxRepetitions("aaa", 3, "aaa", 19))
print(getMaxRepetitions("aaa", 3, "aaa", 20))
print(getMaxRepetitions("aaa", 3, "aaa", 21))
print(getMaxRepetitions("aaa", 3, "aaa", 22))
print(getMaxRepetitions("aaa", 3, "aaa", 23))
print(getMaxRepetitions("aaa", 3, "
