def number_of_steps(n):
    count = 0
    while n > 0:
        if n % 2 == 0:
            n = n/2
            count += 1
        else:
            n = n - 1
            count += 1
    return count
print(number_of_steps(14))
print(number_of_steps(8))
print(number_of_steps(7))
print(number_of_steps(4))
print(number_of_steps(123))
print(number_of_steps(0))
print(number_of_steps(1))
print(number_of_steps(2))
print(number_of_steps(3))
print(number_of_steps(5))
print(number_of_steps(6))
print(number_of_steps(9))
print(number_of_steps(10))
print(number_of_steps(11))
print(number_of_steps(12))
print(number_of_steps(13))
print(number_of_steps(15))
print(number_of_steps(16))
print(number_of_steps(17))
print(number_of_steps(18))
print(number_of_steps(19))
print(number_of_steps(20))
print(number_of_steps(21))
print(number_of_steps(22))
print(number_of_steps(23))
print(number_of_steps(24))
print(number_of_steps(25))
print(number_of_steps(26))
print(number_of_steps(27))
print(number_of_steps(28))
print(number_of_steps(29))
print(number_of_steps(30))
print(number_of_steps(31))
print(number_of_steps(32))
print(number_of_steps(33))
print(number_of_steps(34))
print(number_of_steps(35))
print(number_of_steps(36))
print(number_of_steps(37))
print(number_of_steps(38))
print(number_of_steps(39))
print(number_of_steps(40))
print(number_of_steps(41))
print(number_of_steps(42))
print(number_of_steps(43))
print(number_of_steps(44))
print(number_of_steps(45))
print(number_of_steps(46))
print(number_of_steps(47))
print(number_of_steps(48))
print(number_of_steps(49))
print(number_of_steps(50))
print(number_of_steps(51))
print(number_of_steps(52))
print(number_of_steps(53))
print(number_of_steps(54))
print(number_of_steps(55))
print(number_of_steps(56))
print(number_of_steps(57))
print(number_of_steps(58))
print(number_of_steps(59))
print(number_of_steps(60))
print(number_of_steps
