def minimum_steps(n):
    steps = 0
    while n > 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = n - 1
        steps += 1
    return steps
print(minimum_steps(8))
print(minimum_steps(7))
print(minimum_steps(4))
print(minimum_steps(15))
print(minimum_steps(16))
print(minimum_steps(17))
print(minimum_steps(18))
print(minimum_steps(19))
print(minimum_steps(20))
print(minimum_steps(21))
print(minimum_steps(22))
print(minimum_steps(23))
print(minimum_steps(24))
print(minimum_steps(25))
print(minimum_steps(26))
print(minimum_steps(27))
print(minimum_steps(28))
print(minimum_steps(29))
print(minimum_steps(30))
print(minimum_steps(31))
print(minimum_steps(32))
print(minimum_steps(33))
print(minimum_steps(34))
print(minimum_steps(35))
print(minimum_steps(36))
print(minimum_steps(37))
print(minimum_steps(38))
print(minimum_steps(39))
print(minimum_steps(40))
print(minimum_steps(41))
print(minimum_steps(42))
print(minimum_steps(43))
print(minimum_steps(44))
print(minimum_steps(45))
print(minimum_steps(46))
print(minimum_steps(47))
print(minimum_steps(48))
print(minimum_steps(49))
print(minimum_steps(50))
print(minimum_steps(51))
print(minimum_steps(52))
print(minimum_steps(53))
print(minimum_steps(54))
print(minimum_steps(55))
print(minimum_steps(56))
print(minimum_steps(57))
print(minimum_steps(58))
print(minimum_steps(59))
print(minimum_steps(60))
print(minimum_steps(61))
print(minimum_steps(62))
print(minimum_steps(63))
print(minimum_steps(64))
print(minimum_steps(65))
print(minimum_steps(66))
print(minimum_steps(67))
print(minimum_steps(68))
print(minimum_steps(69))
print(minimum_steps(70))
print(minimum_steps(71))
print(minimum_steps(72))
print(minimum_steps(73))
print(minimum_steps(74))
print(minimum

if __name__ == '__main__':
    minimum_steps()