def uniqueDigits(n):
    if n == 0:
        return 1
    if n == 1:
        return 10
    if n > 10:
        n = 10
    result = 0
    for i in range(10**(n-1), 10**n):
        if len(set(str(i))) == len(str(i)):
            result += 1
    return result
print(uniqueDigits(2))
print(uniqueDigits(0))
print(uniqueDigits(1))
print(uniqueDigits(8))
print(uniqueDigits(9))
print(uniqueDigits(10))
print(uniqueDigits(11))
print(uniqueDigits(12))
print(uniqueDigits(13))
print(uniqueDigits(14))
print(uniqueDigits(15))
print(uniqueDigits(16))
print(uniqueDigits(17))
print(uniqueDigits(18))
print(uniqueDigits(19))
print(uniqueDigits(20))
print(uniqueDigits(21))
print(uniqueDigits(22))
print(uniqueDigits(23))
print(uniqueDigits(24))
print(uniqueDigits(25))
print(uniqueDigits(26))
print(uniqueDigits(27))
print(uniqueDigits(28))
print(uniqueDigits(29))
print(uniqueDigits(30))
print(uniqueDigits(31))
print(uniqueDigits(32))
print(uniqueDigits(33))
print(uniqueDigits(34))
print(uniqueDigits(35))
print(uniqueDigits(36))
print(uniqueDigits(37))
print(uniqueDigits(38))
print(uniqueDigits(39))
print(uniqueDigits(40))
print(uniqueDigits(41))
print(uniqueDigits(42))
print(uniqueDigits(43))
print(uniqueDigits(44))
print(uniqueDigits(45))
print(uniqueDigits(46))
print(uniqueDigits(47))
print(uniqueDigits(48))
print(uniqueDigits(49))
print(uniqueDigits(50))
print(uniqueDigits(51))
print(uniqueDigits(52))
print(uniqueDigits(53))
print(uniqueDigits(54))
print(uniqueDigits(55))
print(uniqueDigits(56))
print(uniqueDigits(57))
print(uniqueDigits(58))
print(uniqueDigits(59))
print(uniqueDigits(60))
print(uniqueDigits(61))
print(uniqueDigits(62))
print(uniqueDigits(63))
print(uniqueDigits(64))
print(uniqueDigits(65))
print(uniqueDigits(66))
print(uniqueDigits(67))
print(uniqueDigits(68))
print(uniqueDigits(69))
print(uniqueDigits(70))
print(uniqueDigits(71))
print(uniqueDigits(72))
print(uniqueDigits(73))
